### ISSUE TITLE
requirements of sklearn

### ISSUE THREAD

**Issue by ZhiyuanChen** [JoshuaRWaite/AI_AFM#1]
The package name of sklearn should be [scikit-learn](https://pypi.org/project/scikit-learn/), the original package of [sklearn](https://pypi.org/project/sklearn/) has been deprecated and in brownout stage.

**Comment by JoshuaRWaite** [comment]
Thanks for letting me know; I'm unsure why sklearn==0.0 was included. I removed it from requirements.txt. However, scikit-learn==1.0.2 was also included, so pip install should still work. Are you getting other version compatibility issues?

**Comment by ZhiyuanChen** [comment]
Thank you so much for your quick response! 
It works very well as of now.
