### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by ZhiyuanChen** [JoshuaRWaite/AI_AFM#3]
Hi, 

Thank you for this excellent work! 

I'm trying to reproduce the reported result on README, following the command on README:

+ 3-Classes: `python main.py -d 3class_matching -m convo1D2 -mod 10 -ep 300 -bs 32 -opt sgd --lr 0.01 -sche_step 1 -sche_gamma 1 -mt triplet -s 0 -exp 4`
+ SR vs Rest: `python main.py -d 2class_s_vs_r -m convo1DS2 -mod 10 -ep 300 -bs 32 -opt sgd --lr 0.01 -sche_step 1 -sche_gamma 1 -mt triplet -g 0 -s 0 -up 0 -exp 5`
+ NR vs Any: `python main.py -d 2class_n_vs_r -m convo1DDrp2 -mod 10 -ep 300 -bs 16 -opt sgd --lr 0.01 -sche_step 1 -sche_gamma 1 -mt triplet -g 0 -s 0 -up 0 -exp 6`

However, there seems to be a gap between the results: 

task | reproduced | Readme
---|---|---
3-Classes | 60.00% | 66.70%
SR vs Rest | 68.33% | 78.30%
NR vs Any | 88.33% | 91.70%

Can I ask if there is anything I'm missing?

**Comment by JoshuaRWaite** [comment]
Hello,

You're welcome; I'm glad you find it interesting!

Unfortunately, there can be variation between runs when training, even after setting the seeds for the various packages. The weights used for the reported results are provided in the logs folder and can be used with the eval.py commands [https://github.com/JoshuaRWaite/AI_AFM#running-few-shot-evaluation-with-pretrained-weights](url).

**Comment by JoshuaRWaite** [comment]
Hello, sorry for such a delayed follow-up. I found an error with some simplifications we did to the data preprocessing. I have since reverted them, and the results now align with those in the paper. Let me know if you have any further questions.
